# https://github.com/codespell-project/codespell#readme
# https://beta.ruff.rs
name: codespell_and_ruff
on:
  push:
  #  branches: [master]
  pull_request:
  #  branches: [master]
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell || true  # --ignore-words-list="" --skip="*.css,*.js,*.lock,*.po"
    - run: ruff --format=github --line-length=103 --select=C4,C9,E9,F63,F7,F82,W --target-version=py310 .
