# https://github.com/codespell-project/codespell#readme
# https://beta.ruff.rs
name: codespell_and_ruff
on:
  push:
  #  branches: [master]
  pull_request:
    branches: [master]
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell --quiet-level=1
    - run: ruff --format=github --line-length=103 --target-version=py310
                --select=C4,C9,E,F,PLE,PLW,W --ignore=E401,F401,F841 .
